#!/usr/bin/env python3
import sys

def file_check(filename):
    try:
        f = open(filename)
        i = 1
        for line in f.readlines():
            # only print output if there's an error line
            if len(line) > 80:
                print('{line}: {length}'.format(line = i, length = len(line)))
            i += 1
        f.close()

    except FileNotFoundError:
        print(filename + ' could not be accessed')


def main():
    for filename in sys.argv:
        file_check(filename)
        print(filename + ' checked')
    print('done')

if __name__ == '__main__':
    main()
