#!/usr/bin/env python        
# Create and save file hashes#
##############################

### NOTE- rename me to filecheck and put me in path ###

import os
import sys
import hashlib

BLOCKSIZE = 65535


def main():
    # check args
    if len(sys.argv) == 1:
        print 'usage: filecheck file1 [file2 ...]'
        exit()

    # make the directory for hashes
    PATH = './hashes/'
    DIR = os.path.dirname(PATH)
    if not os.path.exists(DIR):
        os.makedirs(DIR)

    # make hashes
    iterargs = iter(sys.argv)
    next(iterargs)
    for filename in iterargs:
        with open(PATH + filename + '.hsh', 'w') as f:
            hasher = hashlib.md5()
            with open(filename) as g:
                buf = g.read(BLOCKSIZE)
                while len(buf) > 0:
                    hasher.update(buf)
                    buf = g.read(BLOCKSIZE)
            f.write(hasher.hexdigest())


if __name__ == '__main__':
    main()
